// <auto-generated />
namespace Employes.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v08 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v08));
        
        string IMigrationMetadata.Id
        {
            get { return "202101251109308_v.0.8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
